In [6]:
import torch

a=torch.zeros(2,2)
print(a)


tensor([[0., 0.],
        [0., 0.]])


In [8]:
b=torch.ones(3,3)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
c=torch.rand(2,2)
print(c)

tensor([[0.8926, 0.0152],
        [0.6566, 0.1591]])


In [11]:
d=torch.rand(1,3)
e=torch.rand(1,3)
f=d+e
print(f)

tensor([[0.1331, 0.6033, 0.5298]])


In [12]:
g=torch.rand(3,1)
h=torch.rand(3,1)
i=torch.mul(g,h)
print(i)

tensor([[0.2637],
        [0.5702],
        [0.0822]])


In [13]:
j_data=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
j=torch.tensor(j_data)
print(j)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])


In [14]:
k=torch.rand(3,1)
l=torch.rand(1,3)
m=k/l
print(m)
#Making a local file

tensor([[0.3564, 0.4284, 0.3610],
        [0.6346, 0.7628, 0.6428],
        [0.9558, 1.1489, 0.9682]])
